# This cloudbuild file based on documentation from https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run
# Changes made are based on substitutions from documentation on https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
steps:
# Build the container image
- id: 'Build Docker image for spotifind API'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/spotifind', '.']
# Push the container image to Container Registry
- id: 'Push Docker image for spotifind API to Google Container Registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/spotifind']
# Build the container image for integration tests
- id: 'Build Docker image for spotifind API integration tests'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--network=cloudbuild', '-t', 'gcr.io/${PROJECT_ID}/spotifind-integration-test', '-f', './test/integration_tests/Dockerfile', '.']
# Push the container image for integration tests to Container Registry
- id: 'Push Docker image for spotifind API integration tests to Google Container Registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/spotifind-integration-test']
# Deploy container image for integration tests
- id: 'Deploy Docker image for spotifind API integration tests'
  name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/${PROJECT_ID}/spotifind-integration-test']
# Build container image for deploy component in Kubeflow
- id: 'Build Docker image for Kubeflow deploy component'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/ann_index_deployment', './src/ann_index/']
# Push the container image for Kubeflow deploy component to Container Registry
- id: 'Push Docker image for Kubeflow deploy component to Google Container Registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/ann_index_deployment']
# Deploy container image to GKE
# GKE deployment build step based on documentation from https://cloud.google.com/build/docs/deploying-builds/deploy-gke#automating_deployments
- id: 'Deploy container image for spotifind API'
  name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=deployment.yml
  - --image=gcr.io/${PROJECT_ID}/spotifind
  - --location=${_CLOUDSDK_COMPUTE_ZONE}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
images:
- gcr.io/${PROJECT_ID}/spotifind
- gcr.io/${PROJECT_ID}/spotifind-integration-test
options:
  logging: CLOUD_LOGGING_ONLY
