# This cloudbuild file based on documentation from https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run
# Changes made are based on substitutions from documentation on https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/spotifind', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/spotifind']
# Deploy container image to GKE
# GKE deployment build step based on documentation from https://cloud.google.com/build/docs/deploying-builds/deploy-gke#automating_deployments
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yml
  - --image=gcr.io/${PROJECT_ID}/spotifind
  - --location=${_CLOUDSDK_COMPUTE_ZONE}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
images:
- gcr.io/${PROJECT_ID}/spotifind
