---
apiVersion: v1
kind: Namespace
metadata:
  name: spotifind
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotifind-deployment
  namespace: spotifind
  labels:
    app: spotifind-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spotifind-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: spotifind-app
    spec:
      containers:
      - name: spotifind-app
        image: gcr.io/spotifind-api/spotifind:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: PROJECT_ID
          value: "841506577075"
        - name: PROJECT_NAME
          value: "spotifind-api"
        - name: CLIENT_ID
          value: "081f994d972f46519c1c8f9f6f11102a"
        - name: SECRET_ID
          value: "spotify-rest-api-secret"
        - name: SECRET_VERSION_ID
          value: "latest"
        - name: ENVIRONMENT
          value: "development"
      # Sidecar container for warmups. We take this example directly from the expedia group documentation
      # https://opensource.expediagroup.com/mittens/docs/installation/running#run-as-a-sidecar-on-kubernetes
      - name: mittens
        image: expediagroup/mittens:latest
        resources:
          limits:
            memory: 50Mi
            cpu: 50m
          requests:
            memory: 50Mi
            cpu: 50m
        args:
        - "--concurrency=1"
        - "--max-readiness-wait-seconds=60"
        - "--max-warmup-seconds=30"
        - "--fail-readiness=true"
        - "--file-probe-enabled=false"
        - "--target-readiness-http-path=/health"
        - "--target-readiness-http-host=http://localhost"
        - "--target-readiness-port=5000"
        - "--target-http-host=http://localhost"
        - "--target-http-port=5000"
        - "--http-requests=get:/v1/reco/7cNNUbN90ArXvrfVUcdIO9?size=10"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spotifind-autoscaler
  namespace: spotifind
  labels:
    app: spotifind-deployment-autoscaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: spotifind-deployment
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spotifind-service
  namespace: spotifind
spec:
  selector:
    app: spotifind-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-load-balancer
  namespace: spotifind
  annotations:
    networking.gke.io/managed-certificates: spotifind-external-load-balancer-managed-cert
    kubernetes.io/ingress.global-static-ip-name: spotifind-external-load-balancer-address
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spotifind-service
            port:
              number: 8080
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: spotifind-external-load-balancer-managed-cert
  namespace: spotifind
spec:
  domains:
    - spotifind-api.com
    - www.spotifind-api.com # We also included CNAME in DNS configuration just in case.
