name: ci_pipeline
on:
  pull_request:
    branches:
    - main
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          architecture: 'x64'
          token: ${{ github.token }}
      - run: pip install -r requirements.txt
      - run: python -m unittest discover test/unit_tests/
        # Could not find any documentation on mocking google cloud client libraries for unit tests. We mock credentials as an alternative.
        env:
          GOOGLE_APPLICATION_CREDENTIALS: test/unit_tests/mock_secret.json
