name: ci_pipeline
on:
  pull_request:
    branches:
    - main
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3.0.0
        with:
          python-version: '3.x'
          cache: 'pip'
          architecture: 'x64'
          token: ${{ github.token }}
      - run: pip install -r requirements.txt
      - run: python -m unittest discover test/
